server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/passagens {
        proxy_pass http://passagens:8081/passagens;
    }

    location /api/passageiros {
        proxy_pass http://passageiros:8082/passageiros;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
